package dev.micalobia.extra_things.items;

import dev.micalobia.extra_things.block.NetherBlocks;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroup;

public class NetherItems {
	public static final Item BLUE_NETHERRACK;

	public static final Item CRACKED_NETHER_BRICK_SLAB;
	public static final Item CRACKED_NETHER_BRICK_WALL;
	public static final Item CRACKED_NETHER_BRICK_FENCE;
	public static final Item CRACKED_NETHER_BRICK_STAIRS;
	public static final Item CHISELED_NETHER_BRICK_SLAB;
	public static final Item CHISELED_NETHER_BRICK_WALL;
	public static final Item CHISELED_NETHER_BRICK_FENCE;
	public static final Item CHISELED_NETHER_BRICK_STAIRS;
	public static final Item RED_NETHER_BRICK_FENCE;
	public static final Item RED_CRACKED_NETHER_BRICKS;
	public static final Item RED_CRACKED_NETHER_BRICK_SLAB;
	public static final Item RED_CRACKED_NETHER_BRICK_WALL;
	public static final Item RED_CRACKED_NETHER_BRICK_FENCE;
	public static final Item RED_CRACKED_NETHER_BRICK_STAIRS;
	public static final Item RED_CHISELED_NETHER_BRICKS;
	public static final Item RED_CHISELED_NETHER_BRICK_SLAB;
	public static final Item RED_CHISELED_NETHER_BRICK_WALL;
	public static final Item RED_CHISELED_NETHER_BRICK_FENCE;
	public static final Item RED_CHISELED_NETHER_BRICK_STAIRS;
	public static final Item BLUE_NETHER_BRICKS;
	public static final Item BLUE_NETHER_BRICK_SLAB;
	public static final Item BLUE_NETHER_BRICK_WALL;
	public static final Item BLUE_NETHER_BRICK_FENCE;
	public static final Item BLUE_NETHER_BRICK_STAIRS;
	public static final Item BLUE_CRACKED_NETHER_BRICKS;
	public static final Item BLUE_CRACKED_NETHER_BRICK_SLAB;
	public static final Item BLUE_CRACKED_NETHER_BRICK_WALL;
	public static final Item BLUE_CRACKED_NETHER_BRICK_FENCE;
	public static final Item BLUE_CRACKED_NETHER_BRICK_STAIRS;
	public static final Item BLUE_CHISELED_NETHER_BRICKS;
	public static final Item BLUE_CHISELED_NETHER_BRICK_SLAB;
	public static final Item BLUE_CHISELED_NETHER_BRICK_WALL;
	public static final Item BLUE_CHISELED_NETHER_BRICK_FENCE;
	public static final Item BLUE_CHISELED_NETHER_BRICK_STAIRS;
	public static final Item WARPED_NETHER_BRICKS;
	public static final Item WARPED_NETHER_BRICK_SLAB;
	public static final Item WARPED_NETHER_BRICK_WALL;
	public static final Item WARPED_NETHER_BRICK_FENCE;
	public static final Item WARPED_NETHER_BRICK_STAIRS;
	public static final Item WARPED_CRACKED_NETHER_BRICKS;
	public static final Item WARPED_CRACKED_NETHER_BRICK_SLAB;
	public static final Item WARPED_CRACKED_NETHER_BRICK_WALL;
	public static final Item WARPED_CRACKED_NETHER_BRICK_FENCE;
	public static final Item WARPED_CRACKED_NETHER_BRICK_STAIRS;
	public static final Item WARPED_CHISELED_NETHER_BRICKS;
	public static final Item WARPED_CHISELED_NETHER_BRICK_SLAB;
	public static final Item WARPED_CHISELED_NETHER_BRICK_WALL;
	public static final Item WARPED_CHISELED_NETHER_BRICK_FENCE;
	public static final Item WARPED_CHISELED_NETHER_BRICK_STAIRS;

	static {
		BLUE_NETHERRACK = ModdedItems.register(NetherBlocks.BLUE_NETHERRACK, ItemGroup.BUILDING_BLOCKS);

		CRACKED_NETHER_BRICK_SLAB = ModdedItems.register(NetherBlocks.CRACKED_NETHER_BRICK_SLAB, ItemGroup.BUILDING_BLOCKS);
		CRACKED_NETHER_BRICK_WALL = ModdedItems.register(NetherBlocks.CRACKED_NETHER_BRICK_WALL, ItemGroup.BUILDING_BLOCKS);
		CRACKED_NETHER_BRICK_FENCE = ModdedItems.register(NetherBlocks.CRACKED_NETHER_BRICK_FENCE, ItemGroup.BUILDING_BLOCKS);
		CRACKED_NETHER_BRICK_STAIRS = ModdedItems.register(NetherBlocks.CRACKED_NETHER_BRICK_STAIRS, ItemGroup.BUILDING_BLOCKS);
		CHISELED_NETHER_BRICK_SLAB = ModdedItems.register(NetherBlocks.CHISELED_NETHER_BRICK_SLAB, ItemGroup.BUILDING_BLOCKS);
		CHISELED_NETHER_BRICK_WALL = ModdedItems.register(NetherBlocks.CHISELED_NETHER_BRICK_WALL, ItemGroup.BUILDING_BLOCKS);
		CHISELED_NETHER_BRICK_FENCE = ModdedItems.register(NetherBlocks.CHISELED_NETHER_BRICK_FENCE, ItemGroup.BUILDING_BLOCKS);
		CHISELED_NETHER_BRICK_STAIRS = ModdedItems.register(NetherBlocks.CHISELED_NETHER_BRICK_STAIRS, ItemGroup.BUILDING_BLOCKS);
		RED_NETHER_BRICK_FENCE = ModdedItems.register(NetherBlocks.RED_NETHER_BRICK_FENCE, ItemGroup.BUILDING_BLOCKS);
		RED_CRACKED_NETHER_BRICKS = ModdedItems.register(NetherBlocks.RED_CRACKED_NETHER_BRICKS, ItemGroup.BUILDING_BLOCKS);
		RED_CRACKED_NETHER_BRICK_SLAB = ModdedItems.register(NetherBlocks.RED_CRACKED_NETHER_BRICK_SLAB, ItemGroup.BUILDING_BLOCKS);
		RED_CRACKED_NETHER_BRICK_WALL = ModdedItems.register(NetherBlocks.RED_CRACKED_NETHER_BRICK_WALL, ItemGroup.BUILDING_BLOCKS);
		RED_CRACKED_NETHER_BRICK_FENCE = ModdedItems.register(NetherBlocks.RED_CRACKED_NETHER_BRICK_FENCE, ItemGroup.BUILDING_BLOCKS);
		RED_CRACKED_NETHER_BRICK_STAIRS = ModdedItems.register(NetherBlocks.RED_CRACKED_NETHER_BRICK_STAIRS, ItemGroup.BUILDING_BLOCKS);
		RED_CHISELED_NETHER_BRICKS = ModdedItems.register(NetherBlocks.RED_CHISELED_NETHER_BRICKS, ItemGroup.BUILDING_BLOCKS);
		RED_CHISELED_NETHER_BRICK_SLAB = ModdedItems.register(NetherBlocks.RED_CHISELED_NETHER_BRICK_SLAB, ItemGroup.BUILDING_BLOCKS);
		RED_CHISELED_NETHER_BRICK_WALL = ModdedItems.register(NetherBlocks.RED_CHISELED_NETHER_BRICK_WALL, ItemGroup.BUILDING_BLOCKS);
		RED_CHISELED_NETHER_BRICK_FENCE = ModdedItems.register(NetherBlocks.RED_CHISELED_NETHER_BRICK_FENCE, ItemGroup.BUILDING_BLOCKS);
		RED_CHISELED_NETHER_BRICK_STAIRS = ModdedItems.register(NetherBlocks.RED_CHISELED_NETHER_BRICK_STAIRS, ItemGroup.BUILDING_BLOCKS);
		BLUE_NETHER_BRICKS = ModdedItems.register(NetherBlocks.BLUE_NETHER_BRICKS, ItemGroup.BUILDING_BLOCKS);
		BLUE_NETHER_BRICK_SLAB = ModdedItems.register(NetherBlocks.BLUE_NETHER_BRICK_SLAB, ItemGroup.BUILDING_BLOCKS);
		BLUE_NETHER_BRICK_WALL = ModdedItems.register(NetherBlocks.BLUE_NETHER_BRICK_WALL, ItemGroup.BUILDING_BLOCKS);
		BLUE_NETHER_BRICK_FENCE = ModdedItems.register(NetherBlocks.BLUE_NETHER_BRICK_FENCE, ItemGroup.BUILDING_BLOCKS);
		BLUE_NETHER_BRICK_STAIRS = ModdedItems.register(NetherBlocks.BLUE_NETHER_BRICK_STAIRS, ItemGroup.BUILDING_BLOCKS);
		BLUE_CRACKED_NETHER_BRICKS = ModdedItems.register(NetherBlocks.BLUE_CRACKED_NETHER_BRICKS, ItemGroup.BUILDING_BLOCKS);
		BLUE_CRACKED_NETHER_BRICK_SLAB = ModdedItems.register(NetherBlocks.BLUE_CRACKED_NETHER_BRICK_SLAB, ItemGroup.BUILDING_BLOCKS);
		BLUE_CRACKED_NETHER_BRICK_WALL = ModdedItems.register(NetherBlocks.BLUE_CRACKED_NETHER_BRICK_WALL, ItemGroup.BUILDING_BLOCKS);
		BLUE_CRACKED_NETHER_BRICK_FENCE = ModdedItems.register(NetherBlocks.BLUE_CRACKED_NETHER_BRICK_FENCE, ItemGroup.BUILDING_BLOCKS);
		BLUE_CRACKED_NETHER_BRICK_STAIRS = ModdedItems.register(NetherBlocks.BLUE_CRACKED_NETHER_BRICK_STAIRS, ItemGroup.BUILDING_BLOCKS);
		BLUE_CHISELED_NETHER_BRICKS = ModdedItems.register(NetherBlocks.BLUE_CHISELED_NETHER_BRICKS, ItemGroup.BUILDING_BLOCKS);
		BLUE_CHISELED_NETHER_BRICK_SLAB = ModdedItems.register(NetherBlocks.BLUE_CHISELED_NETHER_BRICK_SLAB, ItemGroup.BUILDING_BLOCKS);
		BLUE_CHISELED_NETHER_BRICK_WALL = ModdedItems.register(NetherBlocks.BLUE_CHISELED_NETHER_BRICK_WALL, ItemGroup.BUILDING_BLOCKS);
		BLUE_CHISELED_NETHER_BRICK_FENCE = ModdedItems.register(NetherBlocks.BLUE_CHISELED_NETHER_BRICK_FENCE, ItemGroup.BUILDING_BLOCKS);
		BLUE_CHISELED_NETHER_BRICK_STAIRS = ModdedItems.register(NetherBlocks.BLUE_CHISELED_NETHER_BRICK_STAIRS, ItemGroup.BUILDING_BLOCKS);
		WARPED_NETHER_BRICKS = ModdedItems.register(NetherBlocks.WARPED_NETHER_BRICKS, ItemGroup.BUILDING_BLOCKS);
		WARPED_NETHER_BRICK_SLAB = ModdedItems.register(NetherBlocks.WARPED_NETHER_BRICK_SLAB, ItemGroup.BUILDING_BLOCKS);
		WARPED_NETHER_BRICK_WALL = ModdedItems.register(NetherBlocks.WARPED_NETHER_BRICK_WALL, ItemGroup.BUILDING_BLOCKS);
		WARPED_NETHER_BRICK_FENCE = ModdedItems.register(NetherBlocks.WARPED_NETHER_BRICK_FENCE, ItemGroup.BUILDING_BLOCKS);
		WARPED_NETHER_BRICK_STAIRS = ModdedItems.register(NetherBlocks.WARPED_NETHER_BRICK_STAIRS, ItemGroup.BUILDING_BLOCKS);
		WARPED_CRACKED_NETHER_BRICKS = ModdedItems.register(NetherBlocks.WARPED_CRACKED_NETHER_BRICKS, ItemGroup.BUILDING_BLOCKS);
		WARPED_CRACKED_NETHER_BRICK_SLAB = ModdedItems.register(NetherBlocks.WARPED_CRACKED_NETHER_BRICK_SLAB, ItemGroup.BUILDING_BLOCKS);
		WARPED_CRACKED_NETHER_BRICK_WALL = ModdedItems.register(NetherBlocks.WARPED_CRACKED_NETHER_BRICK_WALL, ItemGroup.BUILDING_BLOCKS);
		WARPED_CRACKED_NETHER_BRICK_FENCE = ModdedItems.register(NetherBlocks.WARPED_CRACKED_NETHER_BRICK_FENCE, ItemGroup.BUILDING_BLOCKS);
		WARPED_CRACKED_NETHER_BRICK_STAIRS = ModdedItems.register(NetherBlocks.WARPED_CRACKED_NETHER_BRICK_STAIRS, ItemGroup.BUILDING_BLOCKS);
		WARPED_CHISELED_NETHER_BRICKS = ModdedItems.register(NetherBlocks.WARPED_CHISELED_NETHER_BRICKS, ItemGroup.BUILDING_BLOCKS);
		WARPED_CHISELED_NETHER_BRICK_SLAB = ModdedItems.register(NetherBlocks.WARPED_CHISELED_NETHER_BRICK_SLAB, ItemGroup.BUILDING_BLOCKS);
		WARPED_CHISELED_NETHER_BRICK_WALL = ModdedItems.register(NetherBlocks.WARPED_CHISELED_NETHER_BRICK_WALL, ItemGroup.BUILDING_BLOCKS);
		WARPED_CHISELED_NETHER_BRICK_FENCE = ModdedItems.register(NetherBlocks.WARPED_CHISELED_NETHER_BRICK_FENCE, ItemGroup.BUILDING_BLOCKS);
		WARPED_CHISELED_NETHER_BRICK_STAIRS = ModdedItems.register(NetherBlocks.WARPED_CHISELED_NETHER_BRICK_STAIRS, ItemGroup.BUILDING_BLOCKS);


	}

	public static void init() {
	}
}
